application: todolisthack
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets/img/favicon\.ico
  static_files: favicon.ico
  upload: /assets/img/favicon\.ico

- url: /assets
  static_dir: assets

- url: /login
  script: main.app
  secure: always

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
